
services:


  # POSTGRESQL DATABASE
  db:
    image: postgres:17-alpine
    container_name: legal_advisor_db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # FASTAPI BACKEND
  backend:
    build: ./backend
    container_name: legal_advisor_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db



  # STREAMLIT FRONTEND
  frontend:
    build: ./frontend
    container_name: legal_advisor_frontend
    env_file:
      - .env
    ports:
      - "8501:8501"
    depends_on:
      - backend
volumes:
  db_data:
